### ISSUE TITLE
Documentation for v1 top-level API objects seems to be missing

### ISSUE THREAD

**Issue by hausdorff** [kubernetes/kubernetes.github.io#3072]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
The V1 top-level API objects URL now returns a 404: https://kubernetes.io/docs/api-reference/v1/definitions/ But, the equivalent page for extensions/v1beta1 still exists: https://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/

**Proposed Solution:**
This seems like a bug, but I'm not sure where. At this point I'm just wondering if this was on purpose. If it wasn't, then the solution probably involves (1) figuring out what happened, and (2) reversing that.

**Page to Update:**
https://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/

**Comment by jaredbhatti** [comment]
Andrew, can you take a look at this?

**Comment by chenopis** [comment]
The root cause is that we've changed the structure of V1 reference docs. So, for example, `/docs/api-reference/v1/definitions/#_v1_node` should now be `/docs/api-reference/v1.6/#node-v1-core`. Consequently, there's no easy way to write the redirect. I'm still researching what the most efficient solution might be. Stand by.

**Comment by chenopis** [comment]
I have made a change to the redirect.js script to take care of this issue in PR #3160.

**Comment by chenopis** [comment]
These links should work now via a redirect.

**Comment by hausdorff** [comment]
I think this one is still broken? https://kubernetes.io/docs/api-reference/apps/v1beta1/definitions/

**Comment by chenopis** [comment]
@hausdorff Thanks for catching that. I'll work on a patch to address it.

**Comment by chenopis** [comment]
@hausdorff Should be addressed now by PR #3228. PTAL and confirm so we can close this issue. Thx

**Comment by hausdorff** [comment]
@chenopis As a Kubernetes noob, I'm not sure that I'm the right person to sign off, but based on what I understand, this looks good to me. :)

**Comment by chenopis** [comment]
@hausdorff Just wanted to make sure the patch addressed the issue you were seeing. Thanks for submitting the issue and keeping on top of it! =)

**Comment by hausdorff** [comment]
@chenopis I think it is in acceptable shape for my usage. :) The v1beta1 extensions page[1] still seems to point to the old-style version of that page, which is fine for me, but may or may not be what you want -- I'm not sure.

Anyway, thanks for the help!

[1] https://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/

**Comment by chenopis** [comment]
@hausdorff Yeah, we're still working on cleaning that up and other parts of the Reference section. Hopefully, they should be done w/in the next week or so.
